version: '2.1'
services:
  academy-api:
    build: .
    environment:
      PORT: '5000'  
      SHOW_URLS: 'true'
      STUDENTS_URL: '192.168.0.8'
      STUDENTS_PORT: '3001'
      STUDENTS_ENTRY: 'students-ms/resources/students'
      COURSES_URL: '192.168.0.8'
      COURSES_PORT: '3000'
      COURSES_ENTRY: 'courses-ms/resources/courses'
    ports:
      - '5000:5000'